language: php

php:
  - 5.5
  - 5.6
  - 7.3
  - 7.2
  - 7.0

branches:
    only:
        - master 
        #QA/Staging
        - develop 
        #DevServer

before_script:
  composer install --no-interaction

script:
  -vendor/bin/phpunit